### ISSUE TITLE
I can't get Lumina to pull symbols from Lumen (on macOS 15.0.1 AArch64)

### ISSUE THREAD

**Issue by ghost** [tomrus88/OpenLumina#1]
Running **Lumina > Pull All** on IDA Pro 9.0.240925 gives me:
``lumina: Certificate verification failed: unable to get local issuer certificate
Command "LuminaPullAllMds" failed``

The plugin seems to be initializing however?
```
OpenLumina: init
OpenLumina: initialized (Version: Oct  2 2024 11:03:29 64-bit by TOM_RUS)
```

I put in the [Lumen URL with the correct port and put in the user/pw as "guest"](https://github.com/naim94a/lumen/issues/124#issuecomment-2404732898) since that's what @greenozon did and it [presumably works for them?](https://github.com/naim94a/lumen/issues/124#issuecomment-2405647420) but it doesn't work for me.
<img width="831" alt="i" src="https://github.com/user-attachments/assets/4f93d558-823a-4301-a30e-997dd199308a">

Idk what else to do.

**Comment by tomrus88** [comment]
It won't not work with this specific lumina server because it uses incorrectly generated incompatible TLS certificate.

Owner of that server refuses to cooperate/update it with correct one. Nothing I can do about it.

Plugin itself is working correctly and have been tested with both self hosted lumen server and self hosted official lumina server, both are working nicely as long as server uses proper TLS certificate.

Also I see you are on MacOS, I have heard some stories that adding that server certificate to system Keychain allows IDA to successfully connect without even using any plugins, you can try that instead...

Here is how to make it work without using any plugins on MacOS:
- Download hexrays.crt file from [https://abda.nl/lumen/](https://abda.nl/lumen/) page (direct link: https://abda.nl/lumen/hexrays.crt)
- Open Keychain Access app
- Select "System" keychain
- Go to File -> Import Items...
- Select downloaded hexrays.crt file and open it
- Find newly added certificate in the list, double click on it, expand Trust and change default to "Always trust"
- IDA now should be able to connect to lumen.abda.nl lumina server without issues

In theory it should also work on Linux as it uses exact same check, but adding certificate to system store requires different steps here (google how to do that, because I have no idea).

Edit: tried trusted store method on Linux (Ubuntu on WSL) and for some reason it doesn't work here, IDA gives following error:
```
lumina: Certificate verification failed: self-signed certificate
```

Windows is completely different beast and the only way to make it work here is a patch/plugin.

**Comment by ghost** [comment]
Thank you! The keychain method worked.
